name: Smoke Tests

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  Run_Smoke_Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Run Tests
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: test -Dtags=smoke

      - name: Get Allure Report history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: reports
          path: reports/smoke

      - name: Build Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: reports/smoke
          allure_report: smoke/allure-report
          allure_history: smoke/allure-history
          keep_reports: 20
          subfolder: smoke

      - name: Deploy Allure report to Github Pages in the Smoke dir
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: reports
          publish_dir: smoke/allure-history
          keep_files: true